services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - APP_NAME=DevOps-App-Prod
      - DEBUG=False
    restart: always
