services:

  bandit:
    build: ./bandit
    volumes:
      - ./:/app

  semgrep:
    build: ./semgrep
    volumes:
      - ./:/app

  gitleaks:
    build: ./gitleaks
    volumes:
      - ./:/app

  trivy:
    build: ./trivy
    volumes:
      - ./:/app
      - trivy-cache:/root/.cache/trivy
    environment:
      - TRIVY_DB_REPOSITORY=aquasec/trivy-db

  trivy-db-updater:
    build: ./trivy
    volumes:
      - trivy-cache:/root/.cache/trivy
    command: image --download-db-only
    environment:
      - TRIVY_DB_REPOSITORY=mionitra/trivy-db

  pip-audit:
    build: ./pip-audit
    volumes:
      - ./:/app

  cosign:
    build: ./cosign
    volumes:
      - ./:/app

volumes:
  trivy-cache: