services:

  bandit:
    build: ./bandit

  semgrep:
    build: ./semgrep

  gitleaks:
    build: ./gitleaks

  trivy:
    build: ./trivy
    environment:
      - TRIVY_DB_REPOSITORY=aquasec/trivy-db

  trivy-db-updater:
    build: ./trivy
    command: image --download-db-only
    environment:
      - TRIVY_DB_REPOSITORY=mionitra/trivy-db

  pip-audit:
    build: ./pip-audit

  cosign:
    build: ./cosign

volumes:
  trivy-cache: